# Generated by Django 3.1.1 on 2020-12-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201129_1410'),
        ('api', '0002_auto_20201206_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='', max_length=250),
        ),
    ]
